### ISSUE TITLE
UserControl inside ListView

### ISSUE THREAD

**Issue by bcachet** [Prolucid/Elmish.WPF#12]
Hello,

First of all, a huge thanks for this library.
I tryed to develop Unidirectional WPF and I really like your approach.

I am wondering what is the best approach to use an UserControl inside a ListView.

I have started a demo application here: https://github.com/bcachet/Elmish.WPF-Sample/blob/master/src/Counters/App.fs

I have bound the DataContext of the ListView (using Binding.oneWay) but I do not know how to bind DataContext of ListView's items to the ViewBindings representing my UserControl.

Any hint on how to do this ?

Have a nice day

Bertrand

**Comment by 2sComplement** [comment]
Hi Bertrand, thanks for your comment!
This is a good catch, as the type of binding you describe is not yet implemented. I'm working on a sample that will need this as well and hope to have this resolved soon.

**Comment by bcachet** [comment]
That's a really good news. Can't wait to play with it. 
I'm new to F#, but motivated. If I can help, just ask.

**Comment by 2sComplement** [comment]
I've looked in to a few ways of doing this.
Essentially the problem is:

> I want to act on a specific item in a list of record types

The most "elmish" I've come up with so far is to parameterize a single command, with one model containing the list as a regular `oneWay` binding:
```ocaml
    type Item =
        { Id : int
          Value : double }
    type Model =
        { Items : Item list }
    type Msg =
        | Up of int
        | Down of int
    let update msg model =
        let op n i = { i with Value = i.Value + n }
        match msg with
        | Up id -> { model with Items = model.Items |> List.map (fun i -> if i.Id = id then op 1.0 i else i )}
        | Down id -> { model with Items = model.Items |> List.map (fun i -> if i.Id = id then op -1.0 i else i )}
```
You'll notice I added `Id` to the sub model. This is used to uniquely identify the item that should be updated.

So far, pretty elmish and not so bad right? Now for the ugly part. The bindings are going to look for Commands on the DataContext (in this case each `Item` instance) so we need to redirect the binding to the parent:
```xml
<Button Command="{Binding Path=DataContext.Up, RelativeSource={RelativeSource Mode=FindAncestor,AncestorType={x:Type ListView}}}"
        CommandParameter="{Binding Id}">^</Button>
```
The [performance sample](https://github.com/Prolucid/Elmish.WPF/tree/master/src/Samples/Elmish.Samples.Performance) shows this style in use. Ideally I could create some helpers to clean up the XAML, but unfortunately implementing a custom Binding class is not straightforward. Note also that `AncestorType={x:Type ListView}` makes an assumption about the container of these items, which is also not ideal.

I'm definitely open to suggestions on how to improve this.

**Comment by bcachet** [comment]
Hello,

Thanks a lot for this proposition. Good to know that I am able to make things work.
Clearly it's not ideal because with such an implementation, the UserControl is only usable in a ListView, => not really a reusable widget anymore.

I will implement it this way in my sample application in order to better understand how things work.
I will come back to you if I have better suggestion.

Bertrand

**Comment by 2sComplement** [comment]
You're right that with this specific implementation the UserControl assumes that it's contained within a ListView, but you could probably get a bit more generic by using some combination setting `AncestorType` to `UserControl` and playing with the `AncestorLevel`. Let me know if you have any success with that.

**Comment by bcachet** [comment]
Hello,

Your trick worked well. 

But when handling keyboard (KeyBinding) event inside UserControl used as ListViewItem, first key press is handled as expected, but next one is handled by ListView (navigation inside ListView items).
As we recreate the complete ListView when handling updating Model state, the ListView get the focus and so receive following keyboard events.

Live example can be found here: https://github.com/bcachet/Elmish.WPF-Sample/blob/master/src/Counters/App.fs

Any idea on how to fix it ?

Bertrand

**Comment by 2sComplement** [comment]
Sorry for the delay, haven't had a chance to look into this. Will need to investigate a way to maintain focus during updates.
